# Generated by Django 3.1.5 on 2022-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='default_blog.jpg', upload_to='blog_pics'),
        ),
    ]
