# Generated by Django 3.1.5 on 2022-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(default='No audio selected', upload_to='audio_files'),
        ),
    ]
