# Generated by Django 3.1.5 on 2022-09-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='Please add video', upload_to='video_files'),
        ),
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(default='Please add audio', upload_to='audio_files'),
        ),
    ]
