# Generated by Django 3.1.5 on 2022-10-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221001_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
