# Generated by Django 3.1.5 on 2022-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221001_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(default='No audio posted', upload_to='audio_files'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='default_blog.jpg', upload_to='blog_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='No video posted', upload_to='video_files'),
        ),
    ]
