# Generated by Django 3.1.5 on 2022-10-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20221001_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='', max_length=50),
        ),
    ]
