# Generated by Django 3.1.5 on 2022-10-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20221022_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='Please add some tags', max_length=50),
        ),
    ]
