# Generated by Django 3.1.5 on 2022-10-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20221022_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
    ]
