# Generated by Django 3.1.5 on 2023-02-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
