# Generated by Django 3.1.5 on 2023-05-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_image',
        ),
    ]
